version: '3.0'
services:
  mongo:
    image: mongo
    volumes:
      - "./data:/docker-entrypoint-initdb.d"
  job-service:
    build: ../job-service
    image: job-service
    deploy:
      replicas: 2
    depends_on:
      - mongo
    #ports:
    #  - "8111:8111"
    environment: 
      spring.data.mongodb.uri: "mongodb://job_user:job_password@mongo:27017/job"
      #spring.data.mongodb.authentication-database: admin
  candidate-service:
    build:
      context: ../candidate-service/
      dockerfile: ./jdk/Dockerfile
    image: candidate-service
    #profiles:
    # - app
    deploy:
      replicas: 2
    depends_on:
      - mongo
      - job-service
    environment: 
      spring.data.mongodb.uri: "mongodb://candidate_user:candidate_password@mongo:27017/candidate"
      #spring.data.mongodb.authentication-database: admin
      job.service.url: "http://job-service:8111/job/"
  nginx:
    image: nginx
    #profiles:
     # - app
    depends_on: 
      - candidate-service
      - job-service
    ports:
    - "8115:80"
    volumes:
    - "./conf/nginx.conf:/etc/nginx/nginx.conf"
    - "./html/index.html:/usr/share/nginx/html/index.html"