#Not sure why not working
version: "3.0"
services:
  mockserver:
    image: mockserver/mockserver
    ports:
    - "1080:1080"
    environment:
      MOCKSERVER_INTIALIZATION_JSON_PATH: /config/init.json
    volumes:
      - "./config/init.json:/config/init.json"
    